#!/usr/bin/env python3
"""Generate the animated SVG demos in docs/.

Each demo is described declaratively at the bottom of this file:
  - `sequence`: state names to visit (first == last for a smooth loop)
  - `captions`: one string per transition — describes the shortcut that
    caused that move
  - a title, aria-label, footer, and output path

The script computes SVG geometry via the same LayoutCalculator formula Fit
uses at runtime, then emits keyTimes / values for the SMIL animations and
writes the SVG file. Stdlib only — Python 3.9+.

Usage:
    python3 scripts/generate-demos.py
"""

from pathlib import Path
from typing import List, Tuple

# ---------------------------------------------------------------- Geometry --

CARD_W, CARD_H = 900, 680
SCREEN_X, SCREEN_Y, SCREEN_W, SCREEN_H = 30, 30, 840, 500
MENUBAR_H = 30
# Visible frame (area a snapped window fills): screen minus menu bar.
VF_X = SCREEN_X
VF_Y = SCREEN_Y + MENUBAR_H
VF_W = SCREEN_W
VF_H = SCREEN_H - MENUBAR_H
GAP = 6  # matches a small non-zero Fit gap for visual clarity


def snap(col_count: int, col_idx: int, col_span: int,
         row_count: int, row_idx: int, row_span: int) -> Tuple[float, float, float, float]:
    """Fit's LayoutCalculator formula translated to the SVG's visible frame.

    See Fit/Core/LayoutCalculator.swift — the same grid-composition rule.
    """
    unit_w = (VF_W - (col_count + 1) * GAP) / col_count
    unit_h = (VF_H - (row_count + 1) * GAP) / row_count
    x = VF_X + GAP + col_idx * (unit_w + GAP)
    y = VF_Y + GAP + row_idx * (unit_h + GAP)
    w = col_span * unit_w + (col_span - 1) * GAP
    h = row_span * unit_h + (row_span - 1) * GAP
    return (round(x, 1), round(y, 1), round(w, 1), round(h, 1))


# One (x, y, w, h) per named state. `initial` is a hand-picked centered
# small size; the others match Fit's snap actions.
STATES = {
    "initial":           (270, 155, 360, 280),
    "maximize":          snap(1, 0, 1, 1, 0, 1),
    "left_half":         snap(2, 0, 1, 1, 0, 1),
    "right_half":        snap(2, 1, 1, 1, 0, 1),
    "top_half":          snap(1, 0, 1, 2, 0, 1),
    "bottom_half":       snap(1, 0, 1, 2, 1, 1),
    "top_left":          snap(2, 0, 1, 2, 0, 1),
    "top_right":         snap(2, 1, 1, 2, 0, 1),
    "bottom_left":       snap(2, 0, 1, 2, 1, 1),
    "bottom_right":      snap(2, 1, 1, 2, 1, 1),
    "left_third":        snap(3, 0, 1, 1, 0, 1),
    "center_third":      snap(3, 1, 1, 1, 0, 1),
    "right_third":       snap(3, 2, 1, 1, 0, 1),
    "left_two_thirds":   snap(3, 0, 2, 1, 0, 1),
    "right_two_thirds":  snap(3, 1, 2, 1, 0, 1),
    "top_third":         snap(1, 0, 1, 3, 0, 1),
    "middle_third":      snap(1, 0, 1, 3, 1, 1),
    "bottom_third":      snap(1, 0, 1, 3, 2, 1),
    "top_two_thirds":    snap(1, 0, 1, 3, 0, 2),
    "bottom_two_thirds": snap(1, 0, 1, 3, 1, 2),
}

# ------------------------------------------------------------------ Timing --

DWELL = 1.4        # seconds a state is held before moving on
TRANSITION = 0.3   # seconds a value takes to interpolate between states


def timeline(num_states: int) -> Tuple[float, List[float]]:
    """Compute (total duration in seconds, keyTimes as fractions of it).

    Emits two entries per state (start-of-dwell, end-of-dwell). Transitions
    happen between consecutive states' dwells — the animation interpolates
    from `end-of-dwell i` to `start-of-dwell i+1`.
    """
    total = num_states * DWELL + (num_states - 1) * TRANSITION
    times = []
    t = 0.0
    for i in range(num_states):
        times.append(t)
        t += DWELL
        times.append(t)
        if i < num_states - 1:
            t += TRANSITION
    return total, [round(x / total, 4) for x in times]


def caption_keytimes(state_idx: int, num_states: int) -> List[float]:
    """keyTimes for the opacity animation of the caption tied to the
    transition INTO `state_idx` (>=1). Caption fades in as the window starts
    moving into the state, stays visible during the dwell, then fades out as
    the window leaves.
    """
    total = num_states * DWELL + (num_states - 1) * TRANSITION
    t_fade_in_start = state_idx * DWELL + (state_idx - 1) * TRANSITION
    t_arrived = t_fade_in_start + TRANSITION
    t_leave = t_arrived + DWELL
    t_fade_out_end = t_leave + TRANSITION if state_idx < num_states - 1 else total
    return [
        0,
        round(t_fade_in_start / total, 4),
        round(t_arrived / total, 4),
        round(t_leave / total, 4),
        round(t_fade_out_end / total, 4),
        1,
    ]


# -------------------------------------------------------------- Rendering --

TEMPLATE = """<svg viewBox="0 0 900 680" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="{aria}">
  <!-- Generated by scripts/generate-demos.py — edit that script, not this file. -->
  <title>{title}</title>
  <defs>
    <clipPath id="screen-clip"><rect x="30" y="30" width="840" height="500" rx="16"/></clipPath>
    <linearGradient id="win-fill" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#60a5fa"/>
      <stop offset="1" stop-color="#3b82f6"/>
    </linearGradient>
    <linearGradient id="card-bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#0d1117"/>
      <stop offset="1" stop-color="#0b0e14"/>
    </linearGradient>
  </defs>

  <rect width="900" height="680" rx="24" fill="url(#card-bg)"/>
  <rect x="30" y="30" width="840" height="500" rx="16" fill="#161b22" stroke="#30363d" stroke-width="1"/>

  <g clip-path="url(#screen-clip)">
    <rect x="30" y="30" width="840" height="30" fill="#1a1f2b"/>
    <circle cx="46" cy="45" r="2.5" fill="#e5e7eb" opacity="0.7"/>
    <text x="60" y="49" font-family="-apple-system, 'SF Pro Text', sans-serif" font-size="12" fill="#e5e7eb" opacity="0.75">Fit  File  Edit  View</text>
    <text x="852" y="49" text-anchor="end" font-family="-apple-system, 'SF Pro Text', sans-serif" font-size="12" fill="#9ca3af">Wed 12:34</text>

    <g>
      <animateTransform attributeName="transform" type="translate"
        values="{translate}" keyTimes="{keytimes}" dur="{dur}s" repeatCount="indefinite"/>
      <rect x="0" y="0" fill="url(#win-fill)" fill-opacity="0.92"
            stroke="rgba(255,255,255,0.22)" stroke-width="1.5" rx="8">
        <animate attributeName="width" values="{widths}" keyTimes="{keytimes}" dur="{dur}s" repeatCount="indefinite"/>
        <animate attributeName="height" values="{heights}" keyTimes="{keytimes}" dur="{dur}s" repeatCount="indefinite"/>
      </rect>
      <circle cx="20" cy="18" r="6" fill="#ff5f57"/>
      <circle cx="40" cy="18" r="6" fill="#febc2e"/>
      <circle cx="60" cy="18" r="6" fill="#28c840"/>
      <text x="82" y="22" font-family="-apple-system, 'SF Pro Text', sans-serif" font-size="11" font-weight="600" fill="#e5e7eb" opacity="0.85">Fit</text>
    </g>
  </g>

  <rect x="130" y="570" width="640" height="52" rx="26" fill="#161b22" stroke="#30363d" stroke-width="1"/>

  <g font-family="ui-monospace, 'SF Mono', Menlo, Consolas, monospace" font-size="20" fill="#e5e7eb" text-anchor="middle">
{captions}
  </g>

  <text x="450" y="655" font-family="-apple-system, 'SF Pro Text', sans-serif" font-size="13" fill="#6b7280" text-anchor="middle">
    {footer}
  </text>
</svg>
"""


def _n(v):
    """Number → string, dropping trailing zeros for cleaner SVG output."""
    return f"{v:g}"


def _dup(values):
    """Repeat each value twice: [a, b, c] → 'a;a;b;b;c;c' — matches the
    dwell-start / dwell-end keyTimes."""
    return ";".join(_n(v) for v in values for _ in (0, 1))


def render_demo(*, out_path, aria, title, sequence, captions, footer):
    assert len(captions) == len(sequence) - 1, "expected one caption per transition"

    num_states = len(sequence)
    duration, keytimes = timeline(num_states)
    keytimes_str = ";".join(_n(t) for t in keytimes)

    translate_pairs = [f"{_n(STATES[s][0])},{_n(STATES[s][1])}" for s in sequence]
    translate_values = ";".join(v for v in translate_pairs for _ in (0, 1))
    widths = _dup(STATES[s][2] for s in sequence)
    heights = _dup(STATES[s][3] for s in sequence)

    caption_parts = []
    for i, caption in enumerate(captions, start=1):
        kt = ";".join(_n(t) for t in caption_keytimes(i, num_states))
        caption_parts.append(
            f'    <text x="450" y="603">\n'
            f'      <animate attributeName="opacity" values="0;0;1;1;0;0" '
            f'keyTimes="{kt}" dur="{duration:.1f}s" repeatCount="indefinite"/>'
            f'{caption}</text>'
        )

    svg = TEMPLATE.format(
        aria=aria,
        title=title,
        translate=translate_values,
        widths=widths,
        heights=heights,
        keytimes=keytimes_str,
        dur=f"{duration:.1f}",
        captions="\n".join(caption_parts),
        footer=footer,
    )
    Path(out_path).write_text(svg, encoding="utf-8")
    print(f"wrote {out_path}")


# -------------------------------------------------------------------- Demos --

def main():
    repo = Path(__file__).resolve().parent.parent

    render_demo(
        out_path=repo / "docs" / "demo.svg",
        aria="Fit — corner-combining demo",
        title="Fit — half + perpendicular half snaps into a corner",
        sequence=["initial", "left_half", "top_left", "right_half", "bottom_right", "initial"],
        captions=[
            "⌃⌥ ←    left half",
            "⌃⌥ ↑    top-left quarter  (combining halves)",
            "⌃⌥ →    right half",
            "⌃⌥ ↓    bottom-right quarter",
            "⌃⌥ ⌫    restore original size",
        ],
        footer="keyboard only • no drag",
    )

    render_demo(
        out_path=repo / "docs" / "demo-cycle.svg",
        aria="Fit — size cycling demo",
        title="Fit — same shortcut cycles ½ → ⅔ → ⅓ → back to ½",
        sequence=["initial", "left_half", "left_two_thirds", "left_third", "left_half", "initial"],
        captions=[
            "⌃⌥ ←    left half",
            "⌃⌥ ←    left ⅔    (repeat cycles the size)",
            "⌃⌥ ←    left ⅓",
            "⌃⌥ ←    left ½    (cycle wraps back)",
            "⌃⌥ ⌫    restore original size",
        ],
        footer="same shortcut, four presses",
    )


if __name__ == "__main__":
    main()
